{"timestamp":"2025-10-28T12:16:57.377256Z","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-28T12:16:57.378373Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/open_weather_map_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-28T12:16:58.024341Z","level":"info","event":"Transformed weather data into DataFrame","logger":"unusual_prefix_6aa07b989e9bb88d8279bcee7861b87bdad000e6_open_weather_map_dag","filename":"open_weather_map_dag.py","lineno":112}
{"timestamp":"2025-10-28T12:16:58.044815Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"***\" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user \"***\"\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/decorator.py","lineno":252,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/open_weather_map_dag.py","lineno":115,"name":"transform_and_load_weather_data"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/***/hooks/***.py","lineno":281,"name":"get_conn"},{"filename":"/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
